# Generated by Django 5.2.9 on 2026-01-28 09:35

from django.db import migrations
from django.core.files.base import ContentFile
import requests


def create_sample_data(apps, schema_editor):
    BikeCategory = apps.get_model('core', 'BikeCategory')
    Bike = apps.get_model('core', 'Bike')
    
    # Create categories
    categories = [
        {
            'name': 'Mountain Bikes',
            'slug': 'mountain-bikes'
        },
        {
            'name': 'Road Bikes',
            'slug': 'road-bikes'
        },
        {
            'name': 'City Bikes',
            'slug': 'city-bikes'
        },
        {
            'name': 'Electric Bikes',
            'slug': 'electric-bikes'
        }
    ]
    
    created_categories = []
    for cat_data in categories:
        category = BikeCategory.objects.create(**cat_data)
        created_categories.append(category)
    
    # Download and save category images
    category_images = [
        'https://images.unsplash.com/photo-1544191696-19262c03a9a7?w=400&h=300&fit=crop',
        'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=300&fit=crop',
        'https://images.unsplash.com/photo-1571068316344-75bc86f3550c?w=400&h=300&fit=crop',
        'https://images.unsplash.com/photo-1571432248690-5fd963b894c4?w=400&h=300&fit=crop'
    ]
    
    for i, (category, img_url) in enumerate(zip(created_categories, category_images)):
        try:
            response = requests.get(img_url, timeout=10)
            if response.status_code == 200:
                category.image.save(f'category_{category.slug}.jpg', ContentFile(response.content), save=True)
        except:
            pass
    
    # Create bikes
    bikes_data = [
        {
            'name': 'Mountain Explorer Pro',
            'category': created_categories[0],
            'description': 'Professional mountain bike with 21 speeds, perfect for trails and off-road adventures. Features durable frame and suspension system.',
            'price_per_hour': 15.00,
            'price_per_day': 80.00,
            'is_available': True,
        },
        {
            'name': 'Road Racer Elite',
            'category': created_categories[1],
            'description': 'Lightweight carbon fiber road bike designed for maximum speed and efficiency. Perfect for long distance rides.',
            'price_per_hour': 20.00,
            'price_per_day': 120.00,
            'is_available': True,
        },
        {
            'name': 'City Cruiser Comfort',
            'category': created_categories[2],
            'description': 'Comfortable city bike with upright riding position, perfect for daily commuting and urban exploration.',
            'price_per_hour': 10.00,
            'price_per_day': 50.00,
            'is_available': True,
        },
        {
            'name': 'E-Mountain Beast',
            'category': created_categories[3],
            'description': 'Electric mountain bike with powerful 500W motor. Conquer any terrain with ease thanks to electric assistance.',
            'price_per_hour': 25.00,
            'price_per_day': 150.00,
            'is_available': True,
        },
        {
            'name': 'Trail Master X',
            'category': created_categories[0],
            'description': 'All-terrain mountain bike with advanced suspension system. Ready for any trail challenge.',
            'price_per_hour': 18.00,
            'price_per_day': 100.00,
            'is_available': True,
        },
        {
            'name': 'Speed Demon Road',
            'category': created_categories[1],
            'description': 'Ultra-light road bike for competitive cycling. Aerodynamic design for maximum performance.',
            'price_per_hour': 22.00,
            'price_per_day': 130.00,
            'is_available': True,
        },
        {
            'name': 'Urban Commuter Plus',
            'category': created_categories[2],
            'description': 'Practical city bike with rack and fenders. Perfect for daily transportation needs.',
            'price_per_hour': 8.00,
            'price_per_day': 40.00,
            'is_available': True,
        },
        {
            'name': 'E-City Explorer',
            'category': created_categories[3],
            'description': 'Electric city bike with comfortable seating and smooth electric assist. Ideal for urban exploration.',
            'price_per_hour': 12.00,
            'price_per_day': 70.00,
            'is_available': True,
        }
    ]
    
    # Download bike images
    bike_images = [
        'https://images.unsplash.com/photo-1571068316344-75bc86f3550c?w=600&h=400&fit=crop',
        'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&h=400&fit=crop',
        'https://images.unsplash.com/photo-1502744688674-c619d1586c9e?w=600&h=400&fit=crop',
        'https://images.unsplash.com/photo-1571432248690-5fd963b894c4?w=600&h=400&fit=crop',
        'https://images.unsplash.com/photo-1544191696-19262c03a9a7?w=600&h=400&fit=crop',
        'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600&h=400&fit=crop',
        'https://images.unsplash.com/photo-1502744688674-c619d1586c9e?w=600&h=400&fit=crop',
        'https://images.unsplash.com/photo-1571068316344-75bc86f3550c?w=600&h=400&fit=crop'
    ]
    
    created_bikes = []
    for i, bike_data in enumerate(bikes_data):
        bike = Bike.objects.create(**bike_data)
        created_bikes.append(bike)
        
        # Download and save bike image
        try:
            response = requests.get(bike_images[i], timeout=10)
            if response.status_code == 200:
                bike.image.save(f'bike_{bike.name.replace(" ", "_")}.jpg', ContentFile(response.content), save=True)
        except:
            pass


def reverse_sample_data(apps, schema_editor):
    Bike = apps.get_model('core', 'Bike')
    BikeCategory = apps.get_model('core', 'BikeCategory')
    Bike.objects.all().delete()
    BikeCategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_sample_data, reverse_sample_data),
    ]
